<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>pony</string>
	</array>
	<key>name</key>
	<string>Pony</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#block-comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#line-comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#typedeclarations</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#methoddeclarations</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#constants</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#identifiers</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>block-comments</key>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.pony</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#block-comments</string>
				</dict>
			</array>
		</dict>
		<key>constants</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(this)\b</string>
					<key>name</key>
					<string>constant.other.pony</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(true|false)\b</string>
					<key>name</key>
					<string>constant.language.pony</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b((0b[0-1_]*)|(0x[0-9a-fA-F_]*)|([0-9][0-9_]*(\.[0-9][0-9_]*)?((e|E)(\+|-)?[0-9_]+)?))\b</string>
					<key>name</key>
					<string>constant.numeric.pony</string>
				</dict>
			</array>
		</dict>
		<key>methoddeclarations</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.declaration.pony</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.capability.pony</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.pony</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(new|be|fun)\s+(iso|trn|ref|val|box|tag)?\b\s*([_a-z][_a-zA-Z0-9]*)</string>
		</dict>
		<key>typedeclarations</key>
		<dict>
			<key>captures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>keyword.declaration.pony</string>
					</dict>
					<key>2</key>
					<dict>
						<key>name</key>
						<string>keyword.other.capability.pony</string>
					</dict>
					<key>3</key>
					<dict>
						<key>name</key>
						<string>entity.name.type.pony</string>
					</dict>
				</dict>
			<key>match</key>
			<string>\b(type|interface|trait|primitive|struct|class|actor)\s+(iso|trn|ref|val|box|tag)?@?\s*([_A-Z][_a-zA-Z0-9]*)</string>
		</dict>
		<key>identifiers</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.pony</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b([_a-z][_a-zA-Z0-9]*)\b(\(|\[)</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.pony</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\.\s*([_a-z][_a-zA-Z0-9]*)\b[^\(\[]</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.pony</string>
						</dict>
					</dict>
					<key>match</key>
					<string>@\s*([_a-zA-z][_a-zA-Z0-9]*)\s*(\(|\[)</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(_*[A-Z][_a-zA-Z0-9]*)\b</string>
					<key>name</key>
					<string>entity.name.class.pony</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(_*[a-z][_a-zA-Z0-9']*)</string>
					<key>name</key>
					<string></string>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(compile_intrinsic|compile_error)\b</string>
					<key>name</key>
					<string>keyword.other.intrinsic.pony</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(use)\b</string>
					<key>name</key>
					<string>keyword.other.import.pony</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(var|let|embed|delegate)\b</string>
					<key>name</key>
					<string>keyword.other.declaration.pony</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(None|Bool|ISize|ILong|I8|I16|I32|I64|I128|USize|ULong|U8|U16|U32|U64|U128|F32|F64|String)\b</string>
					<key>name</key>
					<string>keyword.other.builtin-type.pony</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(init|final|create|apply|update)\b</string>
					<key>name</key>
					<string>keyword.other.sugar.pony</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(iso|trn|ref|val|box|tag)\b</string>
					<key>name</key>
					<string>entity.other.attribute-name.pony</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(break|continue|return|error)\b</string>
					<key>name</key>
					<string>keyword.control.jump.pony</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(if|ifdef|then|elseif|else|end|match|where|try|with|as|recover|consume|object|lambda|digestof)\b</string>
					<key>name</key>
					<string>keyword.control.pony</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(while|do|repeat|until|for|in)\b</string>
					<key>name</key>
					<string>keyword.control.loop.pony</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\-|\+|\*|/(?![/*])|%|&lt;&lt;|&gt;&gt;)</string>
					<key>name</key>
					<string></string>
				</dict>
				<dict>
					<key>match</key>
					<string>(==|!=|&lt;=|&gt;=|&lt;|&gt;)</string>
					<key>name</key>
					<string></string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(is|isnt|not|and|or|xor)\b</string>
					<key>name</key>
					<string></string>
				</dict>
				<dict>
					<key>match</key>
					<string>=</string>
					<key>name</key>
					<string></string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\?|=&gt;)</string>
					<key>name</key>
					<string></string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\||\&amp;|\,|\^)</string>
					<key>name</key>
					<string></string>
				</dict>
			</array>
		</dict>
		<key>line-comments</key>
		<dict>
			<key>begin</key>
			<string>//</string>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>comment.line.double-slash.pony</string>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.character.begin.pony</string>
						</dict>
					</dict>
					<key>end</key>
					<string>'</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.character.end.pony</string>
						</dict>
					</dict>
					<key>name</key>
					<string>constant.character.pony</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\(?:[abfnrtv\\"0]|x[0-9A-Fa-f]{2})</string>
							<key>name</key>
							<string>constant.character.escape.pony</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>invalid.illegal.pony</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>"""</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.pony</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"""(?!")</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.pony</string>
						</dict>
					</dict>
					<key>name</key>
					<string>variable.parameter.pony</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.pony</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.pony</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.pony</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\(?:[abfnrtv\\"0]|x[0-9A-Fa-f]{2}|u[0-9A-Fa-f]{4}|U[0-9A-Fa-f]{6})</string>
							<key>name</key>
							<string>constant.string.escape.pony</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>invalid.illegal.pony</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.pony</string>
</dict>
</plist>